// src/app/layout.tsx

import type { Metadata } from "next";
// ✅ 1. Import Inter from next/font/google
import { Inter } from "next/font/google"; 
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ 2. Configure the Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // This creates a CSS variable named --font-inter
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ 3. Add the Inter font variable to the body's className */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}